"""
Interactive test script to verify Discord bot commands.

This script helps you test if commands are working properly.
It does NOT start the bot - your bot must be running separately.
"""

import sys

print("=" * 80)
print("Discord Bot Command Testing Guide")
print("=" * 80)
print()
print("⚠️  IMPORTANT: Make sure your bot is running first!")
print("   Start it with: python start.py")
print()
print("=" * 80)
print("COMMANDS TO TEST:")
print("=" * 80)
print()
print("1. >help")
print("   Expected: Bot shows help embed with all available commands")
print()
print("2. >status")
print("   Expected: Bot shows:")
print("   - Configuration (min confidence, analyzers, cooldown)")
print("   - Signals today (total, long, short)")
print("   - Active cooldowns")
print()
print("3. >signal BTC")
print("   Expected: Bot shows latest BTCUSDT signal")
print()
print("4. >signal ETH 4h")
print("   Expected: Bot shows latest ETHUSDT 4h signal")
print()
print("5. >signals 5")
print("   Expected: Bot shows last 5 signals across all symbols")
print()
print("=" * 80)
print("WHAT TO CHECK:")
print("=" * 80)
print()
print("✅ Bot responds to each command")
print("✅ Bot continues running after command (doesn't stop)")
print("✅ Signal generation continues in background")
print("✅ New signals are still sent to Discord")
print()
print("=" * 80)
print("CHECK BOT LOGS FOR:")
print("=" * 80)
print()
print("✅ 'Command \"X\" invoked by...'")
print("✅ 'Command \"X\" completed successfully...'")
print("❌ Any error messages")
print()
print("=" * 80)
print("TESTING PROCEDURE:")
print("=" * 80)
print()
print("1. Make sure bot is running (python start.py)")
print("2. Go to your Discord server")
print("3. Type each command listed above")
print("4. Verify bot responds correctly")
print("5. Watch bot logs for command execution messages")
print("6. Wait a few minutes to see if signals continue")
print()
print("=" * 80)
print("IF COMMANDS DON'T WORK:")
print("=" * 80)
print()
print("1. Check bot logs for errors:")
print("   - 'Error in X command...'")
print("   - 'Command error...'")
print()
print("2. Verify bot has Message Content Intent enabled:")
print("   - Go to Discord Developer Portal")
print("   - Your App → Bot")
print("   - Enable 'Message Content Intent'")
print("   - Restart bot")
print()
print("3. Check bot logs show:")
print("   - 'Registered Discord prefix commands: signal, status, help, signals'")
print("   - 'Total commands registered: 4'")
print()
print("4. Try pinging the bot:")
print("   - Type: @FutureBot")
print("   - If bot doesn't respond, it might not be online")
print()
print("=" * 80)
print("COMMON ISSUES:")
print("=" * 80)
print()
print("❌ Bot shows online but doesn't respond:")
print("   → Message Content Intent not enabled")
print()
print("❌ 'Command not found' error:")
print("   → Commands not registered, check bot logs")
print()
print("❌ Bot responds but then stops:")
print("   → Check for errors in bot logs")
print()
print("❌ Status command fails:")
print("   → Check metrics.get_summary() in logs")
print()
print("=" * 80)
print()
input("Press ENTER when you're ready to test commands in Discord...")
